### ISSUE TITLE
交叉编译失败

### ISSUE THREAD

**Issue by citydirector** [AynaLivePlayer/AynaLivePlayer#25]
尝试在ubuntu24上进行交叉编译，然后抛出了内存错误（或者什么都没生成）
过程：克隆仓库（这里顺便指正readme中https拉取子项目命令应该是：git submodule sync&&git submodule update --init --recursive）
然后执行makefile中三条fyne bundle命令生成bundle.go
最后go build，然后报错内存错误

```
root@pve:~/AynaLivePlayer# go build -o ~/AynaLivePlayer.exe -ldflags -H=windowsgui app/main.go
# command-line-arguments
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6043e5]

goroutine 1 [running]:
cmd/link/internal/ld.(*peSection).emitRelocations(0x0, 0xc00011a0e0, 0xc0061595d0)
        cmd/link/internal/ld/pe.go:406 +0x25
cmd/link/internal/ld.(*peFile).emitRelocations(0x9168c0, 0xc00011e400)
        cmd/link/internal/ld/pe.go:645 +0x546
cmd/link/internal/ld.asmbPe(0xc00011e400)
        cmd/link/internal/ld/pe.go:1761 +0x331
cmd/link/internal/ld.asmb2(0xc00011e400?)
        cmd/link/internal/ld/asmb.go:102 +0xac
cmd/link/internal/ld.Main(_, {0x20, 0x20, 0x1, 0x7, 0x10, 0x0, {0xc0000124f1, 0x1, 0x1}, ...})
        cmd/link/internal/ld/main.go:467 +0x1a6b
main.main()
        cmd/link/main.go:72 +0xddb
```

**Comment by citydirector** [comment]
先声明一下，我很菜，并不会go（
